/* eslint-disable @typescript-eslint/member-ordering */
/**
 * This file was automatically generated by `bwcx-api-client`.
 * DO NOT MODIFY IT BY HAND.
 */

import { AllowedRequestMethod, IBwcxApiRequestAdaptorArgs, AbstractResponseParser } from 'bwcx-api-client';
import { configure as configureUrlcat } from 'urlcat-fork';
import { CreateCollectionReqDTO, CreateCollectionRespDTO, UpdateCollectionReqDTO, GetCollectionsRespDTO, GetPublicCollectionsRespDTO, GetCollectionReqDTO, GetCollectionRespDTO, GetPublicCollectionReqDTO, GetPublicCollectionRespDTO, DeleteCollectionReqDTO } from '../modules/collection/collection.dto';
import { CreateContestReqDTO, CreateContestRespDTO, UpdateContestReqDTO, GetContestsRespDTO, GetPublicContestsRespDTO, ReportPublicContestViewReqDTO, DeleteContestReqDTO, ResetContestEventsReqDTO, AppendContestEventsReqDTO, AppendContestEventsRespDTO, GetPublicContestEventsReqDTO, GetPublicContestEventsRespDTO, StreamPublicContestEventStreamNotificationsReqDTO, GetContestEventStreamReqDTO, GetContestEventStreamRespDTO, GetPublicContestEventStreamReqDTO, GetPublicContestEventStreamRespDTO, DeleteContestEventStreamProducerLockReqDTO, GetContestReqDTO, GetContestRespDTO, GetPublicContestReqDTO, GetPublicContestRespDTO, GetPublicContestUsersReqDTO, GetPublicContestUsersRespDTO, GetPublicContestUserReqDTO, GetPublicContestUserRespDTO, GetContestUsersReqDTO, GetContestUsersRespDTO, GetContestUserReqDTO, GetContestUserRespDTO, UpdateContestUserReqDTO } from '../modules/contest/contest.dto';
import { UploadFileReqDTO, UploadFileRespDTO, GetFileReqDTO, GetFileRespDTO, GetPublicFileReqDTO, GetPublicFileRespDTO, DeleteFileReqDTO } from '../modules/file/file.dto';

const urlcat = configureUrlcat({ arrayFormat: 'repeat' });

export class ApiClient<T = undefined> {
  private readonly _r: (args: IBwcxApiRequestAdaptorArgs<T>) => Promise<any>;
  private readonly _rp: AbstractResponseParser;

  public constructor(
    requestAdapter: { request: (args: IBwcxApiRequestAdaptorArgs<T>) => Promise<any> },
    responseParser: AbstractResponseParser,
  ) {
    this._r = requestAdapter.request;
    this._rp = responseParser;
  }

  /**
   * 创建合集
   *
   * @param {CreateCollectionReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {CreateCollectionRespDTO} The response data (RespDTO).
   */
  public async createCollection(req: CreateCollectionReqDTO, opts?: T): Promise<CreateCollectionRespDTO> {
    return this._r(this._rArgs.a(req, opts)).then((resp) => this._rp.pat(CreateCollectionRespDTO, resp));
  }

  /**
   * 更新合集
   *
   * @param {UpdateCollectionReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateCollection(req: UpdateCollectionReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.b(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 查询全部合集
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetCollectionsRespDTO} The response data (RespDTO).
   */
  public async getCollections(req?: null, opts?: T): Promise<GetCollectionsRespDTO> {
    return this._r(this._rArgs.c(req, opts)).then((resp) => this._rp.pat(GetCollectionsRespDTO, resp));
  }

  /**
   * 公开查询全部合集
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicCollectionsRespDTO} The response data (RespDTO).
   */
  public async getPublicCollections(req?: null, opts?: T): Promise<GetPublicCollectionsRespDTO> {
    return this._r(this._rArgs.d(req, opts)).then((resp) => this._rp.pat(GetPublicCollectionsRespDTO, resp));
  }

  /**
   * 查询合集
   *
   * @param {GetCollectionReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetCollectionRespDTO} The response data (RespDTO).
   */
  public async getCollection(req: GetCollectionReqDTO, opts?: T): Promise<GetCollectionRespDTO> {
    return this._r(this._rArgs.e(req, opts)).then((resp) => this._rp.pat(GetCollectionRespDTO, resp));
  }

  /**
   * 公开查询合集
   *
   * @param {GetPublicCollectionReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicCollectionRespDTO} The response data (RespDTO).
   */
  public async getPublicCollection(req: GetPublicCollectionReqDTO, opts?: T): Promise<GetPublicCollectionRespDTO> {
    return this._r(this._rArgs.f(req, opts)).then((resp) => this._rp.pat(GetPublicCollectionRespDTO, resp));
  }

  /**
   * 删除合集
   *
   * @param {DeleteCollectionReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteCollection(req: DeleteCollectionReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.g(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 创建实时比赛
   *
   * @param {CreateContestReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {CreateContestRespDTO} The response data (RespDTO).
   */
  public async createContest(req: CreateContestReqDTO, opts?: T): Promise<CreateContestRespDTO> {
    return this._r(this._rArgs.h(req, opts)).then((resp) => this._rp.pat(CreateContestRespDTO, resp));
  }

  /**
   * 更新实时比赛
   *
   * @param {UpdateContestReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateContest(req: UpdateContestReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.i(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 查询全部实时比赛
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetContestsRespDTO} The response data (RespDTO).
   */
  public async getContests(req?: null, opts?: T): Promise<GetContestsRespDTO> {
    return this._r(this._rArgs.j(req, opts)).then((resp) => this._rp.pat(GetContestsRespDTO, resp));
  }

  /**
   * 公开查询全部实时比赛
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicContestsRespDTO} The response data (RespDTO).
   */
  public async getPublicContests(req?: null, opts?: T): Promise<GetPublicContestsRespDTO> {
    return this._r(this._rArgs.k(req, opts)).then((resp) => this._rp.pat(GetPublicContestsRespDTO, resp));
  }

  /**
   * 上报一次实时比赛浏览
   *
   * @param {ReportPublicContestViewReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async reportPublicContestView(req: ReportPublicContestViewReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.l(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 删除实时比赛
   *
   * @param {DeleteContestReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteContest(req: DeleteContestReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.m(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 重置实时比赛事件流
   *
   * @param {ResetContestEventsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async resetContestEvents(req: ResetContestEventsReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.n(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 追加实时比赛事件
   *
   * @param {AppendContestEventsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {AppendContestEventsRespDTO} The response data (RespDTO).
   */
  public async appendContestEvents(req: AppendContestEventsReqDTO, opts?: T): Promise<AppendContestEventsRespDTO> {
    return this._r(this._rArgs.o(req, opts)).then((resp) => this._rp.pat(AppendContestEventsRespDTO, resp));
  }

  /**
   * 公开查询实时比赛事件
   *
   * @param {GetPublicContestEventsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicContestEventsRespDTO} The response data (RespDTO).
   */
  public async getPublicContestEvents(req: GetPublicContestEventsReqDTO, opts?: T): Promise<GetPublicContestEventsRespDTO> {
    return this._r(this._rArgs.p(req, opts)).then((resp) => this._rp.pat(GetPublicContestEventsRespDTO, resp));
  }

  /**
   * 公开实时比赛事件流通知
   *
   * @param {StreamPublicContestEventStreamNotificationsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async streamPublicContestEventStreamNotifications(req: StreamPublicContestEventStreamNotificationsReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.q(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 查询实时比赛事件流
   *
   * @param {GetContestEventStreamReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetContestEventStreamRespDTO} The response data (RespDTO).
   */
  public async getContestEventStream(req: GetContestEventStreamReqDTO, opts?: T): Promise<GetContestEventStreamRespDTO> {
    return this._r(this._rArgs.r(req, opts)).then((resp) => this._rp.pat(GetContestEventStreamRespDTO, resp));
  }

  /**
   * 公开查询实时比赛事件流
   *
   * @param {GetPublicContestEventStreamReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicContestEventStreamRespDTO} The response data (RespDTO).
   */
  public async getPublicContestEventStream(req: GetPublicContestEventStreamReqDTO, opts?: T): Promise<GetPublicContestEventStreamRespDTO> {
    return this._r(this._rArgs.s(req, opts)).then((resp) => this._rp.pat(GetPublicContestEventStreamRespDTO, resp));
  }

  /**
   * 释放实时比赛事件流生产者锁
   *
   * @param {DeleteContestEventStreamProducerLockReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetContestEventStreamRespDTO} The response data (RespDTO).
   */
  public async deleteContestEventStreamProducerLock(req: DeleteContestEventStreamProducerLockReqDTO, opts?: T): Promise<GetContestEventStreamRespDTO> {
    return this._r(this._rArgs.t(req, opts)).then((resp) => this._rp.pat(GetContestEventStreamRespDTO, resp));
  }

  /**
   * 查询实时比赛
   *
   * @param {GetContestReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetContestRespDTO} The response data (RespDTO).
   */
  public async getContest(req: GetContestReqDTO, opts?: T): Promise<GetContestRespDTO> {
    return this._r(this._rArgs.u(req, opts)).then((resp) => this._rp.pat(GetContestRespDTO, resp));
  }

  /**
   * 公开查询实时比赛
   *
   * @param {GetPublicContestReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicContestRespDTO} The response data (RespDTO).
   */
  public async getPublicContest(req: GetPublicContestReqDTO, opts?: T): Promise<GetPublicContestRespDTO> {
    return this._r(this._rArgs.v(req, opts)).then((resp) => this._rp.pat(GetPublicContestRespDTO, resp));
  }

  /**
   * 公开查询实时比赛用户
   *
   * @param {GetPublicContestUsersReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicContestUsersRespDTO} The response data (RespDTO).
   */
  public async getPublicContestUsers(req: GetPublicContestUsersReqDTO, opts?: T): Promise<GetPublicContestUsersRespDTO> {
    return this._r(this._rArgs.w(req, opts)).then((resp) => this._rp.pat(GetPublicContestUsersRespDTO, resp));
  }

  /**
   * 公开查询实时比赛用户详情
   *
   * @param {GetPublicContestUserReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicContestUserRespDTO} The response data (RespDTO).
   */
  public async getPublicContestUser(req: GetPublicContestUserReqDTO, opts?: T): Promise<GetPublicContestUserRespDTO> {
    return this._r(this._rArgs.x(req, opts)).then((resp) => this._rp.pat(GetPublicContestUserRespDTO, resp));
  }

  /**
   * 查询实时比赛用户
   *
   * @param {GetContestUsersReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetContestUsersRespDTO} The response data (RespDTO).
   */
  public async getContestUsers(req: GetContestUsersReqDTO, opts?: T): Promise<GetContestUsersRespDTO> {
    return this._r(this._rArgs.y(req, opts)).then((resp) => this._rp.pat(GetContestUsersRespDTO, resp));
  }

  /**
   * 查询实时比赛用户详情
   *
   * @param {GetContestUserReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetContestUserRespDTO} The response data (RespDTO).
   */
  public async getContestUser(req: GetContestUserReqDTO, opts?: T): Promise<GetContestUserRespDTO> {
    return this._r(this._rArgs.z(req, opts)).then((resp) => this._rp.pat(GetContestUserRespDTO, resp));
  }

  /**
   * 更新实时比赛用户
   *
   * @param {UpdateContestUserReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateContestUser(req: UpdateContestUserReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.aa(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 上传比赛文件
   *
   * @param {UploadFileReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {UploadFileRespDTO} The response data (RespDTO).
   */
  public async uploadFile(req: UploadFileReqDTO, opts?: T): Promise<UploadFileRespDTO> {
    return this._r(this._rArgs.ab(req, opts)).then((resp) => this._rp.pat(UploadFileRespDTO, resp));
  }

  /**
   * 查询比赛文件
   *
   * @param {GetFileReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetFileRespDTO} The response data (RespDTO).
   */
  public async getFile(req: GetFileReqDTO, opts?: T): Promise<GetFileRespDTO> {
    return this._r(this._rArgs.ac(req, opts)).then((resp) => this._rp.pat(GetFileRespDTO, resp));
  }

  /**
   * 公开查询比赛文件
   *
   * @param {GetPublicFileReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublicFileRespDTO} The response data (RespDTO).
   */
  public async getPublicFile(req: GetPublicFileReqDTO, opts?: T): Promise<GetPublicFileRespDTO> {
    return this._r(this._rArgs.ad(req, opts)).then((resp) => this._rp.pat(GetPublicFileRespDTO, resp));
  }

  /**
   * 删除比赛文件
   *
   * @param {DeleteFileReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteFile(req: DeleteFileReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.ae(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  private _rArgs = {
    a: (req: CreateCollectionReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/v2/collections', {
          param: {},
          query: {},
        }),
        data: {
          uk: req.uk,
          content: req.content,
        },
        extraOpts: opts,
        metadata: {
          name: 'createCollection',
          method: 'POST',
          path: '/api/v2/collections',
          req: CreateCollectionReqDTO,
          resp: CreateCollectionRespDTO,
        },
      };
    },
    b: (req: UpdateCollectionReqDTO, opts?: any) => {
      return {
        method: 'PATCH' as AllowedRequestMethod,
        url: this._uf('/api/v2/collections/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {
          content: req.content,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateCollection',
          method: 'PATCH',
          path: '/api/v2/collections/:uk',
          req: UpdateCollectionReqDTO,
          resp: null as null,
        },
      };
    },
    c: (req: null, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/collections', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getCollections',
          method: 'GET',
          path: '/api/v2/collections',
          req: null as null,
          resp: GetCollectionsRespDTO,
        },
      };
    },
    d: (req: null, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/collections', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicCollections',
          method: 'GET',
          path: '/api/v2/public/collections',
          req: null as null,
          resp: GetPublicCollectionsRespDTO,
        },
      };
    },
    e: (req: GetCollectionReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/collections/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getCollection',
          method: 'GET',
          path: '/api/v2/collections/:uk',
          req: GetCollectionReqDTO,
          resp: GetCollectionRespDTO,
        },
      };
    },
    f: (req: GetPublicCollectionReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/collections/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicCollection',
          method: 'GET',
          path: '/api/v2/public/collections/:uk',
          req: GetPublicCollectionReqDTO,
          resp: GetPublicCollectionRespDTO,
        },
      };
    },
    g: (req: DeleteCollectionReqDTO, opts?: any) => {
      return {
        method: 'DELETE' as AllowedRequestMethod,
        url: this._uf('/api/v2/collections/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'deleteCollection',
          method: 'DELETE',
          path: '/api/v2/collections/:uk',
          req: DeleteCollectionReqDTO,
          resp: null as null,
        },
      };
    },
    h: (req: CreateContestReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests', {
          param: {},
          query: {},
        }),
        data: {
          uk: req.uk,
          name: req.name,
          title: req.title,
          startAt: req.startAt,
          duration: req.duration,
          frozenDuration: req.frozenDuration,
          banner: req.banner,
          refLinks: req.refLinks,
          problems: req.problems,
          users: req.users,
          markers: req.markers,
          series: req.series,
          sorter: req.sorter,
          contributors: req.contributors,
          redirectUK: req.redirectUK,
        },
        extraOpts: opts,
        metadata: {
          name: 'createContest',
          method: 'POST',
          path: '/api/v2/contests',
          req: CreateContestReqDTO,
          resp: CreateContestRespDTO,
        },
      };
    },
    i: (req: UpdateContestReqDTO, opts?: any) => {
      return {
        method: 'PATCH' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {
          name: req.name,
          title: req.title,
          startAt: req.startAt,
          duration: req.duration,
          frozenDuration: req.frozenDuration,
          banner: req.banner,
          refLinks: req.refLinks,
          problems: req.problems,
          users: req.users,
          markers: req.markers,
          series: req.series,
          sorter: req.sorter,
          contributors: req.contributors,
          srkFileID: req.srkFileID,
          redirectUK: req.redirectUK,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateContest',
          method: 'PATCH',
          path: '/api/v2/contests/:uk',
          req: UpdateContestReqDTO,
          resp: null as null,
        },
      };
    },
    j: (req: null, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getContests',
          method: 'GET',
          path: '/api/v2/contests',
          req: null as null,
          resp: GetContestsRespDTO,
        },
      };
    },
    k: (req: null, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicContests',
          method: 'GET',
          path: '/api/v2/public/contests',
          req: null as null,
          resp: GetPublicContestsRespDTO,
        },
      };
    },
    l: (req: ReportPublicContestViewReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk/views', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'reportPublicContestView',
          method: 'POST',
          path: '/api/v2/public/contests/:uk/views',
          req: ReportPublicContestViewReqDTO,
          resp: null as null,
        },
      };
    },
    m: (req: DeleteContestReqDTO, opts?: any) => {
      return {
        method: 'DELETE' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'deleteContest',
          method: 'DELETE',
          path: '/api/v2/contests/:uk',
          req: DeleteContestReqDTO,
          resp: null as null,
        },
      };
    },
    n: (req: ResetContestEventsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/events/reset', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'resetContestEvents',
          method: 'POST',
          path: '/api/v2/contests/:uk/events/reset',
          req: ResetContestEventsReqDTO,
          resp: null as null,
        },
      };
    },
    o: (req: AppendContestEventsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/events', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {
          streamRevision: req.streamRevision,
          events: req.events,
        },
        extraOpts: opts,
        metadata: {
          name: 'appendContestEvents',
          method: 'POST',
          path: '/api/v2/contests/:uk/events',
          req: AppendContestEventsReqDTO,
          resp: AppendContestEventsRespDTO,
        },
      };
    },
    p: (req: GetPublicContestEventsReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk/events', {
          param: {
            uk: req.uk,
          },
          query: {
            afterEventId: req.afterEventId,
            limit: req.limit,
            streamRevision: req.streamRevision,
            compactProgress: req.compactProgress,
          },
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicContestEvents',
          method: 'GET',
          path: '/api/v2/public/contests/:uk/events',
          req: GetPublicContestEventsReqDTO,
          resp: GetPublicContestEventsRespDTO,
        },
      };
    },
    q: (req: StreamPublicContestEventStreamNotificationsReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk/event-stream/notifications', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'streamPublicContestEventStreamNotifications',
          method: 'GET',
          path: '/api/v2/public/contests/:uk/event-stream/notifications',
          req: StreamPublicContestEventStreamNotificationsReqDTO,
          resp: null as null,
        },
      };
    },
    r: (req: GetContestEventStreamReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/event-stream', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getContestEventStream',
          method: 'GET',
          path: '/api/v2/contests/:uk/event-stream',
          req: GetContestEventStreamReqDTO,
          resp: GetContestEventStreamRespDTO,
        },
      };
    },
    s: (req: GetPublicContestEventStreamReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk/event-stream', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicContestEventStream',
          method: 'GET',
          path: '/api/v2/public/contests/:uk/event-stream',
          req: GetPublicContestEventStreamReqDTO,
          resp: GetPublicContestEventStreamRespDTO,
        },
      };
    },
    t: (req: DeleteContestEventStreamProducerLockReqDTO, opts?: any) => {
      return {
        method: 'DELETE' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/event-stream/producer-lock', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'deleteContestEventStreamProducerLock',
          method: 'DELETE',
          path: '/api/v2/contests/:uk/event-stream/producer-lock',
          req: DeleteContestEventStreamProducerLockReqDTO,
          resp: GetContestEventStreamRespDTO,
        },
      };
    },
    u: (req: GetContestReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getContest',
          method: 'GET',
          path: '/api/v2/contests/:uk',
          req: GetContestReqDTO,
          resp: GetContestRespDTO,
        },
      };
    },
    v: (req: GetPublicContestReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicContest',
          method: 'GET',
          path: '/api/v2/public/contests/:uk',
          req: GetPublicContestReqDTO,
          resp: GetPublicContestRespDTO,
        },
      };
    },
    w: (req: GetPublicContestUsersReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk/users', {
          param: {
            uk: req.uk,
          },
          query: {
            userId: req.userId,
            name: req.name,
            organization: req.organization,
            location: req.location,
            markerId: req.markerId,
            official: req.official,
            teamMemberName: req.teamMemberName,
            banned: req.banned,
          },
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicContestUsers',
          method: 'GET',
          path: '/api/v2/public/contests/:uk/users',
          req: GetPublicContestUsersReqDTO,
          resp: GetPublicContestUsersRespDTO,
        },
      };
    },
    x: (req: GetPublicContestUserReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/contests/:uk/users/:userId', {
          param: {
            uk: req.uk,
            userId: req.userId,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicContestUser',
          method: 'GET',
          path: '/api/v2/public/contests/:uk/users/:userId',
          req: GetPublicContestUserReqDTO,
          resp: GetPublicContestUserRespDTO,
        },
      };
    },
    y: (req: GetContestUsersReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/users', {
          param: {
            uk: req.uk,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getContestUsers',
          method: 'GET',
          path: '/api/v2/contests/:uk/users',
          req: GetContestUsersReqDTO,
          resp: GetContestUsersRespDTO,
        },
      };
    },
    z: (req: GetContestUserReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/users/:userId', {
          param: {
            uk: req.uk,
            userId: req.userId,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getContestUser',
          method: 'GET',
          path: '/api/v2/contests/:uk/users/:userId',
          req: GetContestUserReqDTO,
          resp: GetContestUserRespDTO,
        },
      };
    },
    aa: (req: UpdateContestUserReqDTO, opts?: any) => {
      return {
        method: 'PATCH' as AllowedRequestMethod,
        url: this._uf('/api/v2/contests/:uk/users/:userId', {
          param: {
            uk: req.uk,
            userId: req.userId,
          },
          query: {},
        }),
        data: {
          name: req.name,
          official: req.official,
          avatar: req.avatar,
          photo: req.photo,
          organization: req.organization,
          location: req.location,
          teamMembers: req.teamMembers,
          markers: req.markers,
          banned: req.banned,
          broadcasterToken: req.broadcasterToken,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateContestUser',
          method: 'PATCH',
          path: '/api/v2/contests/:uk/users/:userId',
          req: UpdateContestUserReqDTO,
          resp: null as null,
        },
      };
    },
    ab: (req: UploadFileReqDTO, opts?: any) => {
      const formData = new FormData();
      formData.append('contestId', req.contestId);
      formData.append('category', req.category);
      formData.append('file', req.file);
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/v2/files', {
          param: {},
          query: {},
        }),
        data: formData,
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        extraOpts: opts,
        metadata: {
          name: 'uploadFile',
          method: 'POST',
          path: '/api/v2/files',
          req: UploadFileReqDTO,
          resp: UploadFileRespDTO,
        },
      };
    },
    ac: (req: GetFileReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/files/:id', {
          param: {
            id: req.id,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getFile',
          method: 'GET',
          path: '/api/v2/files/:id',
          req: GetFileReqDTO,
          resp: GetFileRespDTO,
        },
      };
    },
    ad: (req: GetPublicFileReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/v2/public/files/:id', {
          param: {
            id: req.id,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getPublicFile',
          method: 'GET',
          path: '/api/v2/public/files/:id',
          req: GetPublicFileReqDTO,
          resp: GetPublicFileRespDTO,
        },
      };
    },
    ae: (req: DeleteFileReqDTO, opts?: any) => {
      return {
        method: 'DELETE' as AllowedRequestMethod,
        url: this._uf('/api/v2/files/:id', {
          param: {
            id: req.id,
          },
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'deleteFile',
          method: 'DELETE',
          path: '/api/v2/files/:id',
          req: DeleteFileReqDTO,
          resp: null as null,
        },
      };
    },
  }

  private _uf(url: string, extra: { param?: object; query?: object } = {}): string {
    const { param, query } = extra;
    return urlcat(url, {
      ...param,
      ...query,
    });
  }
}
