import 'reflect-metadata';
import type { Newable } from 'bwcx-common';

/**
 * A protobuf message class as generated by protobufjs static modules: it
 * exposes static `decode`/`encode`/`verify`/`fromObject`/`toObject`.
 */
export interface ProtobufMessageType {
  decode: (reader: Uint8Array) => any;
  encode: (message: any) => { finish: () => Uint8Array };
  verify: (message: any) => string | null;
  fromObject: (object: Record<string, unknown>) => any;
  toObject: (message: any, options?: Record<string, unknown>) => Record<string, any>;
}

export interface ProtobufContractMeta {
  /** Message used to decode protobuf request bodies. `null` = no protobuf request. */
  req: ProtobufMessageType | null;
  /** Message used to encode protobuf response bodies. `null` = no protobuf response. */
  resp: ProtobufMessageType | null;
}

const PROTOBUF_CONTRACT_KEY = Symbol.for('rl:protobufContract');

/**
 * Declare that a controller route speaks protobuf. Purely metadata — the
 * generic protobuf middleware and the default response handler read it to
 * decode requests / encode responses. Either side may be omitted.
 *
 * @example
 * `@ProtobufContract(BatchProducerEvent, null)`  // protobuf request, JSON response
 * `@ProtobufContract(null, GetContestEventsResponse)`  // protobuf-capable response
 */
export function ProtobufContract(
  req?: ProtobufMessageType | null,
  resp?: ProtobufMessageType | null,
): MethodDecorator {
  return function (target: Object, propertyKey: string | symbol) {
    const ctor = (target as any).constructor;
    const meta: ProtobufContractMeta = { req: req ?? null, resp: resp ?? null };
    Reflect.defineMetadata(PROTOBUF_CONTRACT_KEY, meta, ctor, propertyKey as string);
  };
}

export function getProtobufContract(
  controller: Newable | Function,
  route: string,
): ProtobufContractMeta | undefined {
  return Reflect.getMetadata(PROTOBUF_CONTRACT_KEY, controller, route);
}
