/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import { parseRoutes, RenderMethodKind } from 'bwcx-client-vue3';

const clientRoutes = parseRoutes([
  {
    name: 'Collection',
    path: '/collection/:id',
    fullPath: '/collection/:id',
    component: () => import(/* webpackChunkName: "Collection" */ '../modules/collection/collection.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Home',
    path: '/',
    fullPath: '/',
    component: () => import(/* webpackChunkName: "Home" */ '../modules/home/home.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'LiveRanklist',
    path: '/live/:id',
    fullPath: '/live/:id',
    component: () => import(/* webpackChunkName: "LiveRanklist" */ '../modules/live/live.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Playground',
    path: '/playground',
    fullPath: '/playground',
    component: () => import(/* webpackChunkName: "Playground" */ '../modules/playground/playground.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.CSR,
    otherOptions: undefined,
  },
  {
    name: 'Ranklist',
    path: '/ranklist/:id',
    fullPath: '/ranklist/:id',
    component: () => import(/* webpackChunkName: "Ranklist" */ '../modules/ranklist/ranklist.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Search',
    path: '/search',
    fullPath: '/search',
    component: () => import(/* webpackChunkName: "Search" */ '../modules/search/search.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
]);

export default clientRoutes;

