/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import { parseRoutes, RenderMethodKind } from 'bwcx-client-vue3';
import { CollectionRPO } from '../../common/modules/collection/collection.rpo';
import { DemoDetailRPO } from '../../common/modules/demo/demo.rpo';
import { LiveRPO } from '../../common/modules/live/live.rpo';
import { RanklistRPO } from '../../common/modules/ranklist/ranklist.rpo';

const clientRoutes = parseRoutes([
  {
    name: 'About',
    path: '/about',
    fullPath: '/about',
    component: () => import(/* webpackChunkName: "About" */ '../modules/about/about.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'Collection',
    path: '/collection/:id',
    fullPath: '/collection/:id',
    component: () => import(/* webpackChunkName: "Collection" */ '../modules/collection/collection.view.vue'),
    routeProps: CollectionRPO,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'DemoDetail',
    path: '/demo/detail/:id',
    fullPath: '/demo/detail/:id',
    component: () => import(/* webpackChunkName: "DemoDetail" */ '../modules/demo/demo-detail.view.vue'),
    routeProps: DemoDetailRPO,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Home',
    path: '/',
    fullPath: '/',
    component: () => import(/* webpackChunkName: "Home" */ '../modules/home/home.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Live',
    path: '/live/:id',
    fullPath: '/live/:id',
    component: () => import(/* webpackChunkName: "Live" */ '../modules/live/live.view.vue'),
    routeProps: LiveRPO,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'Playground',
    path: '/playground',
    fullPath: '/playground',
    component: () => import(/* webpackChunkName: "Playground" */ '../modules/playground/playground.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
  {
    name: 'Ranklist',
    path: '/ranklist/:id',
    fullPath: '/ranklist/:id',
    component: () => import(/* webpackChunkName: "Ranklist" */ '../modules/ranklist/ranklist.view.vue'),
    routeProps: RanklistRPO,
    priority: undefined,
    renderMethod: RenderMethodKind.SSR,
    otherOptions: undefined,
  },
  {
    name: 'Search',
    path: '/search',
    fullPath: '/search',
    component: () => import(/* webpackChunkName: "Search" */ '../modules/search/search.view.vue'),
    routeProps: undefined,
    priority: undefined,
    renderMethod: undefined,
    otherOptions: undefined,
  },
]);

export default clientRoutes;
