/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import '@vue/runtime-core';
import { BwcxVueRouterActions } from 'bwcx-client-vue3';
import * as R from '../../common/router/client-routes';

declare module '@vue/runtime-core' {
  export interface ComponentCustomProperties {
    $$router: {
      to(target: 'Collection'): BwcxVueRouterActions;
      to(target: 'Home'): BwcxVueRouterActions;
      to(target: 'LiveRanklist'): BwcxVueRouterActions;
      to(target: 'Playground'): BwcxVueRouterActions;
      to(target: 'Ranklist'): BwcxVueRouterActions;
      to(target: 'Search'): BwcxVueRouterActions;
    };
  }
}
