/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import { Newable } from 'bwcx-common';
import { RenderMethodKind } from 'bwcx-client-vue/enums';
export const clientRoutesMap = new Map<string, { path: string; routeProps: Newable | undefined; renderMethod: RenderMethodKind | undefined }>([
  ['Collection', { path: '/collection/:id', routeProps: undefined, renderMethod: RenderMethodKind.SSR }],
  ['Home', { path: '/', routeProps: undefined, renderMethod: RenderMethodKind.SSR }],
  ['LiveRanklist', { path: '/live/:id', routeProps: undefined, renderMethod: RenderMethodKind.SSR }],
  ['Playground', { path: '/playground', routeProps: undefined, renderMethod: RenderMethodKind.CSR }],
  ['Ranklist', { path: '/ranklist/:id', routeProps: undefined, renderMethod: RenderMethodKind.SSR }],
  ['Search', { path: '/search', routeProps: undefined, renderMethod: RenderMethodKind.SSR }],
]);

